### ISSUE TITLE
行情刷新频率

### ISSUE THREAD

**Issue by banjuanshua** [daichaoren/stockMarket#3]
你好，你这个是多久调用一次板块信息，如果太快会不会被封ip

**Comment by daichaoren** [comment]
我大概2秒刷新一次，我试了，不会封ip的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: banjuanshua <notifications@github.com>
发送时间: Friday, October 25, 2019 1:11:13 AM
收件人: daichaoren/stockMarket <stockMarket@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [daichaoren/stockMarket] 行情刷新频率 (#3)


你好，你这个是多久调用一次板块信息，如果太快会不会被封ip

―

**Comment by banjuanshua** [comment]
我看你的是选取三个板块，如果同时选取50个呢，会不会导致被封，还有稳定性怎么样呢

**Comment by daichaoren** [comment]
那不是三个板块，是三个板块类型，每个类型下面包含很多板块

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: banjuanshua <notifications@github.com>
发送时间: Friday, October 25, 2019 11:18:05 AM
收件人: daichaoren/stockMarket <stockMarket@noreply.github.com>
抄送: 代超仁 <daichr@live.cn>; Comment <comment@noreply.github.com>
主题: Re: [daichaoren/stockMarket] 行情刷新频率 (#3)


我看你的是选取三个板块，如果同时选取50个呢，会不会导致被封，还有稳定性怎么样呢

―

**Comment by banjuanshua** [comment]
好的，谢谢
